name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:

      - name: Run Script
        run: wget https://raw.githubusercontent.com/DavidWithTuxedo/android_kernel_vivo_y81/kernel-4.9/build.sh && bash build.sh

      - name: Upload ErrLog
        uses: actions/upload-artifact@v2
        with:
          name: error.log
          path: android_kernel_vivo_y81/error.log 
